name = "telegram-worker"
main = "src/index.js"
compatibility_date = "2023-12-01"

# Secrets to be added with wrangler:
# wrangler secret put INTERNAL_SERVICE_KEY
# wrangler secret put TELEGRAM_BOT_TOKEN
# wrangler secret put TELEGRAM_CHAT_ID
