name = "telegram-worker"
account_id = "debc6545e63bea36be059cbc82d80ec8"
main = "src/index.js"
compatibility_date = "2023-12-01"

[observability]
enabled = true

# Secrets to be added with wrangler:
# wrangler secret put INTERNAL_SERVICE_KEY
# wrangler secret put TELEGRAM_BOT_TOKEN
# wrangler secret put TELEGRAM_CHAT_ID
